development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDISCLOUD_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: plant_swap_production
  ssl_params:
      verify_mode: <%= OpenSSL::SSL::VERIFY_NONE %>
